spring:
  application:
    name: InvEntropy
  datasource:
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 附加参数：关闭SSL、开启预处理语句、允许公钥检索（解决本地连接报错）
    url: jdbc:mysql:///inventropy?useSSL=false&useServerPrepStmts=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 数据库登录用户名
    username: ${MYSQL_USER}
    # 数据库登录密码
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: 192.168.100.129
      port: 6379
      password: Lqy147258369
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s



mybatis:
  configuration:
    # MyBatis日志输出：打印SQL到控制台（开发环境调试用）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名映射开关
    map-underscore-to-camel-case: true
  # Mapper XML文件扫描路径
  mapper-locations: classpath:mapper/*.xml


aliyun:
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    bucketName: "inventropy"
    region: "cn-hangzhou"


# SpringDoc API文档自动化配置（适配你的Spring Boot 3.x项目）
springdoc:
  # 自动扫描你的Controller层包路径，替换为你项目Controller的实际包名
  packages-to-scan: com.hsyuan.inventropy.controller
  # Swagger UI在线文档页面配置
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  # 自定义UI访问路径，方便你记忆
    tags-sorter: alpha  # 接口按模块字母排序
    operations-sorter: method  # 接口按请求方法排序
    # 显示 API 的年代久远版本
    show-extensions: true
    # 启用 Try it out 功能
    try-it-out-enabled: true
  # 核心API规范接口（对接你Python自动化脚本的关键地址）
  api-docs:
    enabled: true
    path: /v3/api-docs
  # group-configs 分组配置
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hsyuan.inventropy.controller